-- MySQL Workbench Synchronization
-- Generated: 2026-03-10 15:52
-- Model: New Model
-- Version: 1.0
-- Project: Name of the project
-- Author: ds029

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

ALTER TABLE `token_auth` 
ADD COLUMN `target_user_id` INT(11) NOT NULL AFTER `generated_by_user_id`,
CHANGE COLUMN `id` `id` INT(11) NOT NULL AUTO_INCREMENT ,
ADD INDEX `fk_token_auth_user2_idx` (`target_user_id` ASC);
;

ALTER TABLE `token_auth` 
ADD CONSTRAINT `fk_token_auth_user2`
  FOREIGN KEY (`target_user_id`)
  REFERENCES `user` (`id`)
  ON DELETE NO ACTION
  ON UPDATE NO ACTION;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
